export const GET_HEROES_STARTED = "ENEMY_HERO_STARTED";
export const GET_HEROES_COMPLETED = "GET_HEROES_COMPLETED";
export const GET_HEROES_REJECTED = "GET_HEROES_REJECTED";

export const ENEMY_HEROES_SELECTED = "ENEMY_HEROES_SELECTED";

